/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        canvas: '#faf9f5',
        ink: '#141413',
        body: '#3d3d3a',
        'body-strong': '#252523',
        muted: '#6c6a64',
        'muted-soft': '#8e8b82',
        primary: '#8f482f',
        'primary-active': '#a9583e',
        'primary-disabled': '#e6dfd8',
        'primary-container': '#ad5f45',
        'primary-fixed': '#ffdbd0',
        'primary-fixed-dim': '#ffb59d',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#390c00',
        'on-primary-fixed-variant': '#75331c',
        'on-primary-container': '#fffbff',
        'inverse-primary': '#ffb59d',
        coral: '#cc785c',
        secondary: '#605e5b',
        'secondary-container': '#e6e2de',
        'secondary-fixed': '#e6e2de',
        'secondary-fixed-dim': '#cac6c2',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#666461',
        'on-secondary-fixed': '#1c1b19',
        'on-secondary-fixed-variant': '#484644',
        tertiary: '#00685f',
        'tertiary-container': '#0f8378',
        'tertiary-fixed': '#94f3e6',
        'tertiary-fixed-dim': '#77d7ca',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#f4fffc',
        'on-tertiary-fixed': '#00201d',
        'on-tertiary-fixed-variant': '#005049',
        surface: '#fff8f6',
        'surface-dim': '#e6d7d3',
        'surface-bright': '#fff8f6',
        'surface-soft': '#f5f0e8',
        'surface-card': '#efe9de',
        'surface-cream-strong': '#e8e0d2',
        'surface-dark': '#181715',
        'surface-dark-elevated': '#252320',
        'surface-dark-soft': '#1f1e1b',
        'surface-container': '#faebe6',
        'surface-container-low': '#fff1ed',
        'surface-container-high': '#f4e5e1',
        'surface-container-highest': '#efdfdb',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#924a31',
        'surface-variant': '#efdfdb',
        background: '#fff8f6',
        'on-background': '#211a18',
        'on-surface': '#211a18',
        'on-surface-variant': '#54433e',
        'on-dark': '#faf9f5',
        'on-dark-soft': '#a09d96',
        'inverse-surface': '#372e2c',
        'inverse-on-surface': '#fdede9',
        hairline: '#e6dfd8',
        'hairline-soft': '#ebe6df',
        outline: '#87736d',
        'outline-variant': '#dac1ba',
        'accent-teal': '#5db8a6',
        'accent-amber': '#e8a55a',
        success: '#5db872',
        warning: '#d4a017',
        error: '#c64545',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '96px',
      },
      fontFamily: {
        serif: ['Newsreader', 'Garamond', '"Times New Roman"', 'serif'],
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['64px', { lineHeight: '1.05', letterSpacing: '-1.5px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-1px', fontWeight: '400' }],
        'display-md': ['36px', { lineHeight: '1.15', letterSpacing: '-0.5px', fontWeight: '400' }],
        'display-sm': ['28px', { lineHeight: '1.2', letterSpacing: '-0.3px', fontWeight: '400' }],
        'title-lg': ['22px', { lineHeight: '1.3', letterSpacing: '0px', fontWeight: '500' }],
        'title-md': ['18px', { lineHeight: '1.4', letterSpacing: '0px', fontWeight: '500' }],
        'title-sm': ['16px', { lineHeight: '1.4', letterSpacing: '0px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.55', letterSpacing: '0px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.55', letterSpacing: '0px', fontWeight: '400' }],
        caption: ['13px', { lineHeight: '1.4', letterSpacing: '0px', fontWeight: '500' }],
        'caption-uppercase': ['12px', { lineHeight: '1.4', letterSpacing: '1.5px', fontWeight: '500' }],
        button: ['14px', { lineHeight: '1.0', letterSpacing: '0px', fontWeight: '500' }],
        'nav-link': ['14px', { lineHeight: '1.4', letterSpacing: '0px', fontWeight: '500' }],
      },
      maxWidth: {
        content: '1200px',
      },
    },
  },
  plugins: [],
}
